/**
 * Webpack Module #1153
 * Type: unknown
 */

function (e, t, n) {
    "use strict";
    var o = n(1);
    n(173);
    function i() {}
    o.GObject.inheritAndMix(i, o.GObject);
    var a = null;
    (i.TYPE = {
      UIUX: "preset-uiux",
      SOCIAL: "preset-social",
      PRINT: "preset-print",
      PRESENTATION: "preset-presentation",
      WEB: "preset-web",
      VIDEO: "preset-video",
    }),
      (i.getPresets = function () {
        let e = arguments.length > 0 && void 0 !== arguments[0] && arguments[0];
        return (
          (a && !e) ||
            (a = [
              {
                id: i.TYPE.UIUX,
                name: "UI/UX Design",
                nameEn: "UI/UX Design",
                subTitle: "App & device screens",
                localeClass: null,
                icon: "preset-uiux",
                default: 0,
                layouts: [
                  {
                    id: "iphone-16-pro",
                    name: "iPhone 16 Pro",
                    localeClass: null,
                    unit: "px",
                    width: 393,
                    height: 852,
                  },
                  {
                    id: "iphone-16-pro-max",
                    name: "iPhone 16 Pro Max",
                    localeClass: null,
                    unit: "px",
                    width: 430,
                    height: 932,
                  },
                  {
                    id: "iphone-se",
                    name: "iPhone SE",
                    localeClass: null,
                    unit: "px",
                    width: 375,
                    height: 667,
                  },
                  {
                    id: "samsung-galaxy-s24",
                    name: "Samsung Galaxy S24",
                    localeClass: null,
                    unit: "px",
                    width: 360,
                    height: 780,
                  },
                  {
                    id: "google-pixel-9",
                    name: "Google Pixel 9",
                    localeClass: null,
                    unit: "px",
                    width: 412,
                    height: 892,
                  },
                  {
                    id: "ipad-pro-11",
                    name: "iPad Pro 11\"",
                    localeClass: null,
                    unit: "px",
                    width: 834,
                    height: 1194,
                  },
                  {
                    id: "ipad-pro-13",
                    name: "iPad Pro 13\"",
                    localeClass: null,
                    unit: "px",
                    width: 1024,
                    height: 1366,
                  },
                  {
                    id: "ipad-air",
                    name: "iPad Air",
                    localeClass: null,
                    unit: "px",
                    width: 820,
                    height: 1180,
                  },
                  {
                    id: "android-tablet",
                    name: "Android Tablet",
                    localeClass: null,
                    unit: "px",
                    width: 800,
                    height: 1280,
                  },
                  {
                    id: "apple-watch-ultra",
                    name: "Apple Watch Ultra",
                    localeClass: null,
                    unit: "px",
                    width: 410,
                    height: 502,
                  },
                  {
                    id: "apple-watch-series-9",
                    name: "Apple Watch 45mm",
                    localeClass: null,
                    unit: "px",
                    width: 396,
                    height: 484,
                  },
                  {
                    id: "desktop-1920",
                    name: "Desktop HD",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 1080,
                  },
                  {
                    id: "desktop-1440",
                    name: "Desktop",
                    localeClass: null,
                    unit: "px",
                    width: 1440,
                    height: 900,
                  },
                  {
                    id: "macbook-pro-14",
                    name: "MacBook Pro 14\"",
                    localeClass: null,
                    unit: "px",
                    width: 1512,
                    height: 982,
                  },
                  {
                    id: "surface-pro",
                    name: "Surface Pro",
                    localeClass: null,
                    unit: "px",
                    width: 1368,
                    height: 912,
                  },
                ],
              },
              {
                id: i.TYPE.SOCIAL,
                name: "Social Media",
                nameEn: "Social Media",
                subTitle: "Posts, stories & covers",
                localeClass: null,
                icon: "preset-social",
                layouts: [
                  {
                    id: "instagram-post",
                    name: "Instagram Post",
                    localeClass: null,
                    unit: "px",
                    width: 1080,
                    height: 1080,
                  },
                  {
                    id: "instagram-story",
                    name: "Instagram Story / Reel",
                    localeClass: null,
                    unit: "px",
                    width: 1080,
                    height: 1920,
                  },
                  {
                    id: "instagram-landscape",
                    name: "Instagram Landscape",
                    localeClass: null,
                    unit: "px",
                    width: 1080,
                    height: 566,
                  },
                  {
                    id: "instagram-portrait",
                    name: "Instagram Portrait",
                    localeClass: null,
                    unit: "px",
                    width: 1080,
                    height: 1350,
                  },
                  {
                    id: "tiktok-video",
                    name: "TikTok Video",
                    localeClass: null,
                    unit: "px",
                    width: 1080,
                    height: 1920,
                  },
                  {
                    id: "youtube-thumbnail",
                    name: "YouTube Thumbnail",
                    localeClass: null,
                    unit: "px",
                    width: 1280,
                    height: 720,
                  },
                  {
                    id: "youtube-banner",
                    name: "YouTube Channel Art",
                    localeClass: null,
                    unit: "px",
                    width: 2560,
                    height: 1440,
                  },
                  {
                    id: "facebook-post",
                    name: "Facebook Post",
                    localeClass: null,
                    unit: "px",
                    width: 1200,
                    height: 630,
                  },
                  {
                    id: "facebook-cover",
                    name: "Facebook Cover",
                    localeClass: null,
                    unit: "px",
                    width: 820,
                    height: 312,
                  },
                  {
                    id: "facebook-story",
                    name: "Facebook Story",
                    localeClass: null,
                    unit: "px",
                    width: 1080,
                    height: 1920,
                  },
                  {
                    id: "x-post",
                    name: "X (Twitter) Post",
                    localeClass: null,
                    unit: "px",
                    width: 1600,
                    height: 900,
                  },
                  {
                    id: "x-header",
                    name: "X (Twitter) Header",
                    localeClass: null,
                    unit: "px",
                    width: 1500,
                    height: 500,
                  },
                  {
                    id: "linkedin-post",
                    name: "LinkedIn Post",
                    localeClass: null,
                    unit: "px",
                    width: 1200,
                    height: 1200,
                  },
                  {
                    id: "linkedin-cover",
                    name: "LinkedIn Cover",
                    localeClass: null,
                    unit: "px",
                    width: 1584,
                    height: 396,
                  },
                  {
                    id: "pinterest-pin",
                    name: "Pinterest Pin",
                    localeClass: null,
                    unit: "px",
                    width: 1000,
                    height: 1500,
                  },
                  {
                    id: "threads-post",
                    name: "Threads Post",
                    localeClass: null,
                    unit: "px",
                    width: 1080,
                    height: 1080,
                  },
                  {
                    id: "dribbble-shot",
                    name: "Dribbble Shot",
                    localeClass: null,
                    unit: "px",
                    width: 1600,
                    height: 1200,
                  },
                ],
              },
              {
                id: i.TYPE.PRINT,
                name: "Print",
                nameEn: "Print",
                subTitle: "Paper & physical media",
                localeClass: null,
                icon: "preset-print",
                default: 4,
                layouts: [
                  {
                    id: "a3",
                    name: "A3",
                    localeClass: null,
                    unit: "mm",
                    width: 297,
                    height: 420,
                    dpi: 300,
                  },
                  {
                    id: "a4",
                    name: "A4",
                    localeClass: null,
                    unit: "mm",
                    width: 210,
                    height: 297,
                    dpi: 300,
                  },
                  {
                    id: "a5",
                    name: "A5",
                    localeClass: null,
                    unit: "mm",
                    width: 148,
                    height: 210,
                    dpi: 300,
                  },
                  {
                    id: "us-letter",
                    name: "US Letter",
                    localeClass: null,
                    unit: "in",
                    width: 8.5,
                    height: 11,
                    dpi: 300,
                  },
                  {
                    id: "us-legal",
                    name: "US Legal",
                    localeClass: null,
                    unit: "in",
                    width: 8.5,
                    height: 14,
                    dpi: 300,
                  },
                  {
                    id: "us-tabloid",
                    name: "Tabloid (11x17)",
                    localeClass: null,
                    unit: "in",
                    width: 11,
                    height: 17,
                    dpi: 300,
                  },
                  {
                    id: "business-card",
                    name: "Business Card",
                    localeClass: null,
                    unit: "mm",
                    width: 85,
                    height: 55,
                    dpi: 300,
                  },
                  {
                    id: "postcard",
                    name: "Postcard (4x6)",
                    localeClass: null,
                    unit: "in",
                    width: 6,
                    height: 4,
                    dpi: 300,
                  },
                  {
                    id: "poster-18x24",
                    name: "Poster (18x24)",
                    localeClass: null,
                    unit: "in",
                    width: 18,
                    height: 24,
                    dpi: 300,
                  },
                  {
                    id: "poster-24x36",
                    name: "Poster (24x36)",
                    localeClass: null,
                    unit: "in",
                    width: 24,
                    height: 36,
                    dpi: 300,
                  },
                  {
                    id: "flyer",
                    name: "Flyer (5x7)",
                    localeClass: null,
                    unit: "in",
                    width: 5,
                    height: 7,
                    dpi: 300,
                  },
                  {
                    id: "brochure",
                    name: "Brochure Tri-fold",
                    localeClass: null,
                    unit: "in",
                    width: 11,
                    height: 8.5,
                    dpi: 300,
                  },
                ],
              },
              {
                id: i.TYPE.PRESENTATION,
                name: "Presentation",
                nameEn: "Presentation",
                subTitle: "Slides & decks",
                localeClass: null,
                icon: "preset-presentation",
                default: 0,
                layouts: [
                  {
                    id: "slide-16-9",
                    name: "Widescreen (16:9)",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 1080,
                  },
                  {
                    id: "slide-4-3",
                    name: "Standard (4:3)",
                    localeClass: null,
                    unit: "px",
                    width: 1024,
                    height: 768,
                  },
                  {
                    id: "slide-16-10",
                    name: "Widescreen (16:10)",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 1200,
                  },
                  {
                    id: "google-slides",
                    name: "Google Slides",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 1080,
                  },
                  {
                    id: "keynote",
                    name: "Keynote",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 1080,
                  },
                  {
                    id: "powerpoint",
                    name: "PowerPoint",
                    localeClass: null,
                    unit: "in",
                    width: 13.333,
                    height: 7.5,
                    dpi: 96,
                  },
                  {
                    id: "pitch-deck",
                    name: "Pitch Deck",
                    localeClass: null,
                    unit: "px",
                    width: 1280,
                    height: 720,
                  },
                  {
                    id: "a4-landscape",
                    name: "A4 Landscape",
                    localeClass: null,
                    unit: "mm",
                    width: 297,
                    height: 210,
                    dpi: 150,
                  },
                ],
              },
              {
                id: i.TYPE.WEB,
                name: "Web",
                nameEn: "Web",
                subTitle: "Websites & banners",
                localeClass: null,
                icon: "preset-web",
                layouts: [
                  {
                    id: "web-1920",
                    name: "Desktop HD (1920)",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 1080,
                  },
                  {
                    id: "web-1440",
                    name: "Desktop (1440)",
                    localeClass: null,
                    unit: "px",
                    width: 1440,
                    height: 900,
                  },
                  {
                    id: "web-1366",
                    name: "Laptop (1366)",
                    localeClass: null,
                    unit: "px",
                    width: 1366,
                    height: 768,
                  },
                  {
                    id: "web-1280",
                    name: "Small Desktop (1280)",
                    localeClass: null,
                    unit: "px",
                    width: 1280,
                    height: 800,
                  },
                  {
                    id: "web-full-page",
                    name: "Full Page (1440)",
                    localeClass: null,
                    unit: "px",
                    width: 1440,
                    height: 3072,
                  },
                  {
                    id: "web-landing",
                    name: "Landing Page",
                    localeClass: null,
                    unit: "px",
                    width: 1440,
                    height: 2560,
                  },
                  {
                    id: "web-hero",
                    name: "Hero Banner",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 600,
                  },
                  {
                    id: "web-leaderboard",
                    name: "Leaderboard Ad",
                    localeClass: null,
                    unit: "px",
                    width: 728,
                    height: 90,
                  },
                  {
                    id: "web-medium-rect",
                    name: "Medium Rectangle Ad",
                    localeClass: null,
                    unit: "px",
                    width: 300,
                    height: 250,
                  },
                  {
                    id: "email-header",
                    name: "Email Header",
                    localeClass: null,
                    unit: "px",
                    width: 600,
                    height: 200,
                  },
                  {
                    id: "favicon",
                    name: "Favicon",
                    localeClass: null,
                    unit: "px",
                    width: 512,
                    height: 512,
                  },
                  {
                    id: "og-image",
                    name: "Open Graph Image",
                    localeClass: null,
                    unit: "px",
                    width: 1200,
                    height: 630,
                  },
                ],
              },
              {
                id: i.TYPE.VIDEO,
                name: "Video / Motion",
                nameEn: "Video / Motion",
                subTitle: "Video & animation frames",
                localeClass: null,
                icon: "preset-video",
                layouts: [
                  {
                    id: "video-1080p",
                    name: "Full HD (1080p)",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 1080,
                  },
                  {
                    id: "video-4k",
                    name: "4K UHD",
                    localeClass: null,
                    unit: "px",
                    width: 3840,
                    height: 2160,
                  },
                  {
                    id: "video-720p",
                    name: "HD (720p)",
                    localeClass: null,
                    unit: "px",
                    width: 1280,
                    height: 720,
                  },
                  {
                    id: "video-2k",
                    name: "2K (1440p)",
                    localeClass: null,
                    unit: "px",
                    width: 2560,
                    height: 1440,
                  },
                  {
                    id: "vertical-video",
                    name: "Vertical Video (9:16)",
                    localeClass: null,
                    unit: "px",
                    width: 1080,
                    height: 1920,
                  },
                  {
                    id: "square-video",
                    name: "Square Video (1:1)",
                    localeClass: null,
                    unit: "px",
                    width: 1080,
                    height: 1080,
                  },
                  {
                    id: "youtube-thumbnail",
                    name: "YouTube Thumbnail",
                    localeClass: null,
                    unit: "px",
                    width: 1280,
                    height: 720,
                  },
                  {
                    id: "youtube-end-screen",
                    name: "YouTube End Screen",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 1080,
                  },
                  {
                    id: "twitch-overlay",
                    name: "Twitch Overlay",
                    localeClass: null,
                    unit: "px",
                    width: 1920,
                    height: 1080,
                  },
                  {
                    id: "cinema-scope",
                    name: "Cinemascope (2.39:1)",
                    localeClass: null,
                    unit: "px",
                    width: 2560,
                    height: 1072,
                  },
                ],
              },
            ]),
          a
        );
      }),
      (e.exports = i);
  }